# -*- coding: utf-8 -*-
"""PythonAssignment11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ke8yw9oNamaQPbF_lqnsHiLpq2_DfFXc
"""

#!pip install googlesearch-python
#!pip install google
#!pip install beautifulsoup4
from googlesearch import search

def google_search(query):
    search_results = search(query)

    for idx, result in enumerate(search_results, start=1):
        print(f"{idx}. {result}")

query = input("Enter your search query: ")
google_search(query)

#!pip install geopy
from geopy.geocoders import Nominatim

def get_location_info(location_name):
    geolocator = Nominatim(user_agent="location_script")
    location = geolocator.geocode(location_name)

    if location:
        print("Location Information:")
        print(f"Latitude: {location.latitude}")
        print(f"Longitude: {location.longitude}")
        print(f"Address: {location.address}")
        print(f"City: {location.raw.get('address', {}).get('city', 'N/A')}")
        print(f"State: {location.raw.get('address', {}).get('state', 'N/A')}")
        print(f"Country: {location.raw.get('address', {}).get('country', 'N/A')}")
    else:
        print("Location not found.")

if __name__ == "__main__":
    location_name = input("Enter the location name: ")
    get_location_info(location_name)

#!pip install requests
import requests
import sys

def get_weather(api_key, city_id):
    base_url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
        "id": city_id,
        "appid": api_key,
        "units": "metric"
    }

    response = requests.get(base_url, params=params)

    if response.status_code == 200:
        data = response.json()

        temperature = data["main"]["temp"]
        temp_min = data["main"]["temp_min"]
        temp_max = data["main"]["temp_max"]
        windspeed = data["wind"]["speed"]
        humidity = data["main"]["humidity"]
        cloud_coverage = data["clouds"]["all"]
        pressure = data["main"]["pressure"]
        sunrise = data["sys"]["sunrise"]
        sunset = data["sys"]["sunset"]

        print("Environmental Parameters:")
        print(f"Temperature: {temperature}°C (Min: {temp_min}°C, Max: {temp_max}°C)")
        print(f"Windspeed: {windspeed} m/s")
        print(f"Humidity: {humidity}%")
        print(f"Cloud Coverage: {cloud_coverage}%")
        print(f"Pressure: {pressure} hPa")
        print(f"Sunrise: {sunrise}")
        print(f"Sunset: {sunset}")
    else:
        print("Failed to fetch weather data.")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python weather.py <API_KEY> <CITY_ID>")
        sys.exit(1)

    api_key = sys.argv[1]
    city_id = sys.argv[2]

    get_weather(api_key, city_id)

